[package]
name = "storage-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
libnexus = { path = "../libnexus" }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
anyhow = "1"
